### ISSUE TITLE
generate the base 64 format and utf-8 for test cases

### ISSUE THREAD

**Issue by crystaljesica** [Iostream3100/Studio-Web#101]
these lines can help us to console log the base64 file and utf-8

I would temperorily add them to our demo.component.ts file, so that in this case, after I run the demo, I could get the result I want for the test cases.

```
var newtextXML = this.b64Service.b64_to_utf8( this.b64Inputs[1].substring(this.b64Inputs[1].indexOf(",") + 1) ); 
    console.log("====consle.log base64===="); 
    console.log( this.b64Inputs[1].substring(this.b64Inputs[1].indexOf(",") + 1)); 
    const newparser = new DOMParser();
    const newdoc = newparser.parseFromString(newtextXML, "application/xml"); 
    console.log("=====consle.log utf8=============="); 
    console.log(newdoc); 
```

**Comment by crystaljesica** [comment]
![image](https://user-images.githubusercontent.com/90473229/204413825-f07d02fd-5f73-4b47-9916-af9389e32369.png)

**Comment by guanxiaotongyz** [comment]
This method is so great way to test and debug, In Real implement process, I will print b64code and xml code both, It can  clearly see the element and know how to insert it. any way. great
