### ISSUE TITLE
Gruop meeting with Eric 11.30

### ISSUE THREAD

**Issue by yoxchen95** [Iostream3100/Studio-Web#105]
- Eric likes what it is right now.
- Make the buttons clear. Fix the style for the buttons.
- Left line would be better.
- Milestone2 can be considered as done except for some unit testes.
- When delete the images, the input files button don't show the name of files.
- Merge all the milestones into one new branch. Don't need to pull request.
- Send the final demo time to Eric.

**Comment by crystaljesica** [comment]
Thanks for the meeting note!

Our project seems well implemented. Eric is very satisfied with our process now. We would meet him again in the final demo day.

Before the demo day, we would finish implementing all the features and merge our code into one branch. I would also add several releases for our project as well as the demo video!

Great job! Appreciate everyone's hard work!
