### ISSUE TITLE
Translation line hidden in html

### ISSUE THREAD

**Issue by guanxiaotongyz** [Iostream3100/Studio-Web#106]

**Comment by guanxiaotongyz** [comment]
On download page, when User click right below icon , the translation line can be hidden and will be show on click again.

**Comment by guanxiaotongyz** [comment]
<img width="1199" alt="Screen Shot 2022-11-30 at 10 13 18 PM" src="https://user-images.githubusercontent.com/94739229/204979506-2e0a6a2d-6b87-414c-baa1-65494f03841a.png">
<img width="1187" alt="Screen Shot 2022-11-30 at 10 14 01 PM" src="https://user-images.githubusercontent.com/94739229/204979521-05509ce9-827a-47b8-9470-5f94770197bb.png">

**Comment by guanxiaotongyz** [comment]
This this example file ：

**Comment by crystaljesica** [comment]
As we mentioned in today's meeting with Eric, if this function can work successfully, it means that our component is written correctly and can connect with the read-along.tsx component.

The other two icons also work correctly. That's pretty user friendly.
