### ISSUE TITLE
Research on Angular Test Query Selector 

### ISSUE THREAD

**Issue by Iostream3100** [Iostream3100/Studio-Web#12]
What are the options for selecting an element using a query selector in Angular tests?

**Comment by guanxiaotongyz** [comment]
For angular query some denotes should be notice:

- One method is using debugElement method and id/class name to query.
 

`const { debugElement } = fixture;`
`const title1 = debugElement.query(By.css('#spanid')).nativeElement;`

- before query element, should determine if an element is visible or not based solely on the boolean result of an *ngIf directive
  
   If the element is hidden, then it wont be rendered inside the dom.
   You can check:
`expect(fixture.debugElement.query(By.css('.header'))).toBeNull();`

**Comment by guanxiaotongyz** [comment]
How to test *ngif ?

We can also test the *ngIf s and check that the correct components are showing when they should be. We can write one test to check the component is showing when the condition is true, and one test to check the component isn’t showing when the condition is false. If the conditional statement of the *ngIfis more complicated, then you could write more unit tests

reference:
https://javascript.plainenglish.io/9-html-template-unit-tests-to-write-for-angular-apps-f1970b2cda4e#b9cf

**Comment by crystaljesica** [comment]
How to test clicking a button in angular?

Previously I didn't think about using the 'async' and 'spyOn' when I am writing the test. Below is the reference that I found on the stackoverflow.

```
`it('should', async(() => {
  spyOn(component, 'onEditButtonClick');

  let button = fixture.debugElement.nativeElement.querySelector('button');
  button.click();

  fixture.whenStable().then(() => {
    expect(component.onEditButtonClick).toHaveBeenCalled();
  });
}));`

```
this is the similar test to what we have learned in class.

reference:https://stackoverflow.com/questions/40093013/unit-testing-click-event-in-angular

**Comment by yoxchen95** [comment]
Basic of testing components

The Angular [TestBed](https://angular.io/api/core/testing/TestBed) facilitates this kind of testing as you'll see in the following sections. But in many cases, testing the component class alone, without DOM involvement, can validate much of the component's behavior in a straightforward, more obvious way.

re:https://angular.io/guide/testing-components-basics


An example of mock translateservice with angular test

re:https://stackoverflow.com/questions/65243847/jest-angular-testing-library-mock-translateservice
