### ISSUE TITLE
Test for Editable Subtitle

### ISSUE THREAD

**Issue by guanxiaotongyz** [Iostream3100/Studio-Web#15]

**Comment by guanxiaotongyz** [comment]
Using angular test framework:

- check the create file success

- check the original value

- check the editable value

**Comment by guanxiaotongyz** [comment]
![Image](https://user-images.githubusercontent.com/94739229/197087540-d174ca43-febc-4376-9a98-a82a19fc7849.png)

**Comment by yoxchen95** [comment]
To test whether it is the right value to change subtitle value
![image](https://user-images.githubusercontent.com/98132024/197102539-c975d44d-1df8-4179-897f-875098245d19.png)
![image](https://user-images.githubusercontent.com/98132024/197102690-2a0af677-f4bb-40cf-a3fb-76d114bf587c.png)
