### ISSUE TITLE
analyze the lifecycle of download

### ISSUE THREAD

**Issue by crystaljesica** [Iostream3100/Studio-Web#61]
When we are trying to including the function code inside the download, we always use the append to add the new input area for the user, however, when clicking the button, the order of the input is not correct. It always has one line ahead. Need to fix this.

**Comment by guanxiaotongyz** [comment]
<img width="1059" alt="Screen Shot 2022-11-10 at 12 20 19 PM" src="https://user-images.githubusercontent.com/94739229/201198539-18660843-84a6-4c77-8dc9-ac4a79d261f3.png">
<img width="1076" alt="Screen Shot 2022-11-10 at 12 20 27 PM" src="https://user-images.githubusercontent.com/94739229/201198553-e725dd92-90c1-4348-a511-f8ef1c584599.png">

**Comment by crystaljesica** [comment]
Here is some resources that I find regarding to angular life cycle:

link: https://angular.io/guide/lifecycle-hooks

Assumption: may need to use ngDoCheck() to check the input.

![image](https://user-images.githubusercontent.com/90473229/201203914-4d495da2-4b8f-419d-895b-f901e681de92.png)
