### ISSUE TITLE
【bug】when the editable element equals to 'true', the element in html is not editable

### ISSUE THREAD

**Issue by crystaljesica** [Iostream3100/Studio-Web#67]
Bug to be solved:
fixed the editable element can't be edited in the web page.

![image](https://user-images.githubusercontent.com/90473229/201605433-88468dd7-24e3-44ce-9a9c-47012d4395a2.png)

**Comment by crystaljesica** [comment]
solved this bug by creating a add event listener and let user enter the translation
![image](https://user-images.githubusercontent.com/90473229/202123579-ecc92326-b2ed-4f27-9f0e-cbc526cb4740.png)

**Comment by guanxiaotongyz** [comment]
For this problem，we concentrate on b64input[1] too much,
we should change another idea , 
1.insert input tag/ contentiable span in  shawdow of read-longs
2. pass the new html"shawdow of read-longs" to new b64input[1]

specific detail
 #77
