### ISSUE TITLE
Meeting with Eric & Aiden (Nov 16)

### ISSUE THREAD

**Issue by yoxchen95** [Iostream3100/Studio-Web#73]
Milestone2:
web-componet input doesn't need to be b64input
Question about the position of buttons 
Demo
<img width="271" alt="image" src="https://user-images.githubusercontent.com/98132024/202271587-fcd8deaf-6f80-404b-bf1e-b8bd63eb1e36.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/98132024/202271627-d98b892a-28c8-4976-8a5c-43fd0459556f.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/98132024/202271710-9a233fed-5a16-4c6f-9650-0f3d791d343c.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/98132024/202271850-dc32444b-271a-4f88-a959-2863f64e82a5.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/98132024/202273772-3aa6aa8e-044b-4609-b307-82d6c3e7da09.png">

set EDIT or other mode
<img width="322" alt="image" src="https://user-images.githubusercontent.com/98132024/202272028-f22f2901-412d-4f7e-96cb-d9fe3cdea747.png">

Add new buttons to delete or change images

(About images url)
<img width="395" alt="image" src="https://user-images.githubusercontent.com/98132024/202275175-91d6c93e-0aa8-4704-ba14-61636e0f8a7c.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/98132024/202275413-7f759058-1f9d-4ac5-892b-4b1e89b05845.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/98132024/202277744-f122a7fc-ee4b-4050-a6d3-8e4018d73bd8.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/98132024/202278014-d99c7deb-f7e2-4310-a1a4-7102c2282215.png">

In readme.md useAssetsFolder

Milestone3:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/98132024/202281222-fb2d4be6-9f9c-4e2e-b2c0-184e80fdc1d2.png">
It is good for now.

**Comment by guanxiaotongyz** [comment]
the note is perfect, and for the milestone3 have some little hints/requirements that Eric mentioned.
1. each translation line should be below the original line(branch) rather than at back of original line
2. it is better to add two languages, but this  extra task

**Comment by crystaljesica** [comment]
Based on Eric's advice, we made some changes to milestone3

- update the position of the translation line by adding additional <br> element inside the inner HTML
- update the button with better css decorator
- make the translation able to be deleted or modified after the original update
- inspiration from Eric and Aidan how the web component connect each part of the code
