### ISSUE TITLE
modify the translation and the sentence in the format

### ISSUE THREAD

**Issue by crystaljesica** [Iostream3100/Studio-Web#74]
able to add the translation under each line and able to insert/ delete

![image](https://user-images.githubusercontent.com/90473229/202322449-913bb636-957e-4d63-b102-fa97e6953ce0.png)

**Comment by guanxiaotongyz** [comment]
For this function,
1. We select `shadowRoot` of read-along, 
2. query each `sentence`.
3. addEventlistener click , when click shows span with contenteditable

**Comment by yoxchen95** [comment]
If we can add two lines to add two languages for translation, it would be better.
And this function also inspires me some thoughts about milestone2
