### ISSUE TITLE
fixe bug for input line below the Original line

### ISSUE THREAD

**Issue by guanxiaotongyz** [Iostream3100/Studio-Web#76]
` sentence.insertAdjacentHTML(
          "beforeend",
          '<br><span class = "translation" contenteditable = True>Translation</span>'
        );`

**Comment by guanxiaotongyz** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

**Comment by crystaljesica** [comment]
this is a very good practice of using insetAdjacentHTML in different positions.
Here is a relevant recourse: https://www.w3schools.com/jsref/met_node_insertadjacenthtml.asp
