### ISSUE TITLE
 logic of adding translation line 

### ISSUE THREAD

**Issue by guanxiaotongyz** [Iostream3100/Studio-Web#77]
For milestone3 We have two parts
1. modify the translation and the sentence in the format
2. Download the file with translation line

For first part, #74 

For second Part, 1) convert base64 to utf8 from b64input[1] , 2) add translation line to html(utf8) 3) convert html with new translation line to b64input[1] #75

**Comment by crystaljesica** [comment]
Thanks Xiaotong for your generalization of the logic of milestoen3.
For the download part, we also needs to have a converting xml function to update the element inside the download function.
