### ISSUE TITLE
Test for Editable Page Title 

### ISSUE THREAD

**Issue by Iostream3100** [Iostream3100/Studio-Web#8]
Subtask of #1 
Test for #7 

Using angular test framework:
- check the create file success
- check the original value
- check the editable value

**Comment by crystaljesica** [comment]
- test for edit multiple times

![image](https://user-images.githubusercontent.com/90473229/197080969-413546b1-7683-43ee-adb1-6a18aeddbcd5.png)

- test for subtitles empty

![image](https://user-images.githubusercontent.com/90473229/197081013-4130b41a-498f-47cd-a419-029137415708.png)

- test for subtitles default

![image](https://user-images.githubusercontent.com/90473229/197081022-d681d1bb-34eb-472f-aa92-fad4a0f9266d.png)
![image](https://user-images.githubusercontent.com/90473229/197081034-1e909bc3-94d8-4254-8fc4-e8a41e13cef7.png)

**Comment by guanxiaotongyz** [comment]
Using Angular test Framwork:

https://testing-angular.com/testing-components/#writing-the-first-component-spec

Some special tests need:

- empty
- multiple  edited value
