### ISSUE TITLE
fix the test of milestone1

### ISSUE THREAD

**Issue by crystaljesica** [Iostream3100/Studio-Web#82]
after modify the milestone3, we made some changes based on the code of milestone1.
Our test also influenced from the change of milestone3.

![image](https://user-images.githubusercontent.com/90473229/203474506-a08fed9f-7f14-45e5-a9df-2731b7194105.png)

**Comment by guanxiaotongyz** [comment]
The main reason is the constructor add one attribute, B64Service:
```
constructor(public titleService: Title, public b64Service: B64Service) {
    titleService.setTitle(this.slots.pageTitle);
  }
```

One possible method is revise test instance.

**Comment by crystaljesica** [comment]
this is the resource I am looking at: https://stackoverflow.com/questions/47236963/no-provider-for-httpclient

One of the possible reason is that we haven't import the httpclient
![image](https://user-images.githubusercontent.com/90473229/203721760-0220431d-6549-44a4-97af-d94d3b02ecd5.png)

**Comment by crystaljesica** [comment]
【bug fixed】

after searching for resources, I found out that this is a very common error in angular while testing.

We should include the `import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';`

Instead of imports the material model, we should import the http model.

```
beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      declarations: [DemoComponent],
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    }).compileComponents();
```
