### ISSUE TITLE
Fix just can add one translation line by one line 

### ISSUE THREAD

**Issue by guanxiaotongyz** [Iostream3100/Studio-Web#84]
Original picture, it can add infinite translation line, will effect User Experience:
The demo image:
<img width="1131" alt="Screen Shot 2022-11-23 at 7 35 25 PM" src="https://user-images.githubusercontent.com/94739229/203688594-1c10b038-7609-494f-863a-ba0603c0d3a9.png">

After fixed,  one line just insert one translation line: 
<img width="1148" alt="Screen Shot 2022-11-23 at 7 34 43 PM" src="https://user-images.githubusercontent.com/94739229/203688637-29a4f8aa-ac26-423c-a4aa-7264f2c02b21.png">

**Comment by guanxiaotongyz** [comment]
The specific code,, we set flag to done it:
```
button.addEventListener("click", () => {
        if (!this.clicked) {
          this.clicked = true;
          sentence.insertAdjacentHTML(
                  "beforeend",
                  '<br><span class = "translation" contenteditable = True>Translation</span>'
                );  
        }
      });
```

**Comment by guanxiaotongyz** [comment]
The above solution is not work in case that need add more translation lines:

new solution that use setAttribute to solve it.

```
sentences.forEach((sentence: any) => {
      const button = document.createElement("button");
      
      button.innerHTML = "Button";
      sentence.insertAdjacentElement("afterend", button);
      button.addEventListener("click", () => {
          sentence.insertAdjacentHTML(
                  "beforeend",
                  '<br><span class = "translation" contenteditable = True>Translation</span>'
                );
          button.setAttribute("disabled", "true");
      });
    });
```

**Comment by crystaljesica** [comment]
【bug fixed】The previous code using setattribute is not working when user enter the translation

I use the original JavaScript method to set the button's 'disable' = true

```
addTranslationLine(): void {
    // @ts-ignore
    const readalongRoot: any = document.querySelector("read-along").shadowRoot;
    const sentences = readalongRoot.querySelectorAll(".sentence");
    sentences.forEach((sentence: any) => {
      const innerbutton = document.createElement("button");
      innerbutton.innerHTML = "Button";
      // innerbutton.setAttribute("click", "clicked = true");
      innerbutton.addEventListener("click", () => {
        sentence.insertAdjacentHTML(
          "beforeend",
          '<br><span class = "translation" contenteditable = True>Translation</span>'
        );
        innerbutton.disabled = true;
      });
      sentence.insertAdjacentElement("afterend", innerbutton);
    });
  }
```

**Comment by guanxiaotongyz** [comment]
<img width="939" alt="Screen Shot 2022-11-23 at 10 39 50 PM" src="https://user-images.githubusercontent.com/94739229/203712287-55390142-67b2-4ec9-a580-bf071fc87203.png">
