### ISSUE TITLE
Test for Editable Title

### ISSUE THREAD

**Issue by Iostream3100** [Iostream3100/Studio-Web#9]
Subtask of #1 
Test for #6 

Using angular test framework:

- check the create file success
- check the original value
- check the editable value

**Comment by guanxiaotongyz** [comment]
1. Using Angular test Framwork:

    https://testing-angular.com/testing-components/#writing-the-first-component-spec


2. Some special tests need:

- empty
- multiple  edited value 

3.  *ngif test 
    #12

**Comment by guanxiaotongyz** [comment]
![Image](https://user-images.githubusercontent.com/94739229/197087511-1aba67b8-0e51-4262-bb0f-abedbc6176f0.png)
