### ISSUE TITLE
Node version issue

### ISSUE THREAD

**Issue by guanxiaotongyz** [Iostream3100/Studio-Web#90]
Because of Eric repo update, the node version also changed, It  has a little effect the milestone3:
Therefore, I open two brach 

"add-translation-line" brach can use node version16  below version 
"milestone3" branch can just only use node version16  and above

Hint:
if you want switch other version, you should npm install again

**Comment by crystaljesica** [comment]
Additional notice:

when you are using the "add-translation-line" brach, please remember also to update the ''SoundswallowerService.ts" file.
