### ISSUE TITLE
Problem to find the location of the subpage

### ISSUE THREAD

**Issue by yoxchen95** [Iostream3100/Studio-Web#95]
When adding the two buttons(url and local_file), I want to insert these buttons into the end of the page instead of just behind the images. But it seems to have one problem here.
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/98132024/203885131-9d1fd313-7476-4d22-bf15-0a66276657f1.png">
I try to use queryselctor to catch the page page__container page--multi animate-transition theme--light class and insert buttons before its end. But I can catch that.
And after testing, only two things can be caught (sentence and image).
It seems I got stucked here.
[https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll](url)
MDN for querySelctorall

**Comment by yoxchen95** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/98132024/203885351-dc65deb3-5e1b-4ebc-8fbc-b10881f48f69.png">

**Comment by crystaljesica** [comment]
Hi yongxiang,

I find some link might be useful:
https://stackoverflow.com/questions/55970545/how-to-find-subpage-elements-using-javascript
https://blog.angular-university.io/angular2-router/

**Comment by yoxchen95** [comment]
> Hi yongxiang,
> 
> I find some link might be useful: https://stackoverflow.com/questions/55970545/how-to-find-subpage-elements-using-javascript https://blog.angular-university.io/angular2-router/

Thank you so much!

**Comment by yoxchen95** [comment]
And yun give another hint: just use web container to queryselect

const imageContainers = readalongRoot.querySelectorAll(".image__container");

and insert the button just after the start of the imageContainers
