### ISSUE TITLE
analyse the import model for milestone3 test cases

### ISSUE THREAD

**Issue by crystaljesica** [Iostream3100/Studio-Web#98]
Since our milestone3 modified the constructor and need to convert the XML into the download function,

For the previous model we import, they can't support the base 64 service.

In this case, I import the 'HttpClient' and 'B64Service' to support the test cases

```
import { HttpClientModule } from "@angular/common/http";
import { HttpClient, HttpEventType } from "@angular/common/http";
import { B64Service } from "../b64.service";
```

**Comment by crystaljesica** [comment]
This is the link about testing the http client: https://angular.io/guide/testing-services

Might be useful for milestone2.

**Comment by guanxiaotongyz** [comment]
We meet those problems in writing milestone3 test. This great job
